#!/usr/bin/env python3
"""Generate docs/PRODUCT_CATALOG.md from plotter/config/config.yaml."""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from plotter.core.config_loader import load_param_config

CATALOG_PATH = ROOT / "docs" / "PRODUCT_CATALOG.md"
MAPS_ROOT = ROOT / "assets" / "maps"
# Param may contain digits (e.g. rain_rh700); the 3-digit hour suffix anchors the split.
FILE_PATTERN = re.compile(r"^(?P<param>[a-z0-9_]+)_(?P<hour>\d{3})\.webp$")

STATUS_ORDER = ("production", "ready", "stub")


def scan_deployed_assets():
    """Return {dataset: {region: {param: [hours]}}}."""
    deployed = {}
    if not MAPS_ROOT.is_dir():
        return deployed

    for dataset_dir in sorted(MAPS_ROOT.iterdir()):
        if not dataset_dir.is_dir() or dataset_dir.name.startswith("."):
            continue
        regions = {}
        for region_dir in sorted(dataset_dir.iterdir()):
            if not region_dir.is_dir():
                continue
            params = {}
            for f in region_dir.glob("*.webp"):
                m = FILE_PATTERN.match(f.name)
                if m:
                    params.setdefault(m.group("param"), []).append(m.group("hour"))
            if params:
                for p in params:
                    params[p] = sorted(set(params[p]))
                regions[region_dir.name] = params
        if regions:
            deployed[dataset_dir.name] = regions
    return deployed


def format_colormap(var_cfg):
    palette = var_cfg.get("palette")
    if palette:
        return f"`{palette}` (Nusawave)"
    cmap = var_cfg.get("cmap")
    if isinstance(cmap, list):
        return f"custom discrete ({len(cmap)} colors)"
    if cmap:
        return str(cmap)
    return "—"


def format_levels(var_cfg):
    levels = var_cfg.get("levels")
    clims = var_cfg.get("clims")
    if isinstance(levels, dict):
        return f"{levels['start']}–{levels['end']} step {levels['step']}"
    if isinstance(levels, list):
        if len(levels) <= 6:
            return ", ".join(str(x) for x in levels)
        return f"{levels[0]}–{levels[-1]} ({len(levels)} bins)"
    if clims:
        return f"clims {clims}"
    return "—"


def deployment_note(slug, product, deployed):
    dataset = product.get("dataset", "")
    ds_data = deployed.get(dataset, {})
    if not ds_data:
        return "not deployed"

    region_count = 0
    hour_sets = []
    for region, params in ds_data.items():
        if slug in params:
            region_count += 1
            hour_sets.append(set(params[slug]))

    if region_count == 0:
        return "not deployed"

    hours = sorted(set.intersection(*hour_sets)) if hour_sets else []
    hour_labels = ", ".join(f"F{h}" for h in hours) if hours else "—"
    return f"{region_count} region(s), {hour_labels}"


def build_taxonomy_rows(products):
    rows = []
    for slug, product in sorted(products.items()):
        plot = product.get("plot", {})
        scalar = plot.get("scalar", {})
        vector = plot.get("vector", {})
        colorbar = plot.get("colorbar", {})
        rows.append(
            (
                slug,
                scalar.get("method") or "—",
                vector.get("method") if vector.get("overlay") or vector.get("method") not in (None, "none") else "—",
                "yes" if colorbar.get("enabled") else "no",
            )
        )
    return rows


def render_markdown(yaml_cfg, deployed):
    products = yaml_cfg.get("products", {})
    variables = yaml_cfg.get("variables", {})
    regions = list(yaml_cfg.get("regions", {}).keys())
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    by_status = {s: [] for s in STATUS_ORDER}
    for slug, product in products.items():
        status = product.get("status", "ready")
        by_status.setdefault(status, []).append((slug, product))

    lines = [
        "# Map Forecast Product Catalog",
        "",
        "> Auto-generated by `scripts/generate_product_catalog.py`. Do not edit by hand.",
        "",
        f"Last updated: **{now}**",
        "",
        "## Progress summary",
        "",
        "| Status | Count | Products |",
        "|--------|-------|----------|",
    ]

    for status in STATUS_ORDER:
        items = by_status.get(status, [])
        names = ", ".join(f"`{s}`" for s, _ in items) or "—"
        lines.append(f"| **{status}** | {len(items)} | {names} |")

    lines.extend(
        [
            "",
            f"- **Regions configured:** {len(regions)} (`{', '.join(regions)}`)",
            f"- **Datasets with deployed maps:** {', '.join(sorted(deployed)) or 'none'}",
            "",
            "## Rendering pipeline",
            "",
            "```mermaid",
            "flowchart TB",
            "    GRIB[GRIB or NetCDF] --> Plotter[plotter/core/plotter.py]",
            "    Plotter --> Handler[plotter/handlers]",
            "    Handler --> Scalar[scalar layer]",
            "    Handler --> Vector[vector overlay optional]",
            "    Plotter --> Colorbar[horizontal colorbar]",
            "    Plotter --> Legend[direction legend]",
            "    Plotter --> WebP[assets/maps/dataset/region/param_HHH.webp]",
            "    WebP --> ConfigJSON[assets/config/config.json]",
            "    ConfigJSON --> Frontend[src/main.js]",
            "```",
            "",
            "## Plot-type taxonomy",
            "",
            "| Product | Scalar | Vector | Colorbar |",
            "|---------|--------|--------|----------|",
        ]
    )

    for slug, scalar, vector, cbar in build_taxonomy_rows(products):
        lines.append(f"| `{slug}` | {scalar} | {vector} | {cbar} |")

    lines.extend(
        [
            "",
            "### Plot methods",
            "",
            "| Method | Matplotlib API | Use case |",
            "|--------|----------------|----------|",
            "| **Discrete shaded** | `contourf` or `pcolormesh` + `ListedColormap` + `BoundaryNorm` | All filled scalar products |",
            "| **Line contour** | `contour` + `clabel` | MSLP isobars (no fill) |",
            "| **Filled anomaly** | `contourf` + Nusawave diverging palette | SSH |",
            "| **Vector overlay** | `quiver` or `barbs` | Wind/wave direction, sea current |",
            "",
            "### Colorbar and legend",
            "",
            "- Horizontal colorbar below the map (65% axes width), when `plot.colorbar.enabled` is true.",
            "- Tick labels from `variables.*.levels` or implicit pcolormesh scale.",
            "- Unit label in monospace to the right of the bar.",
            "- Direction legend: quiver reference arrow, or windbarb convention note when `plot.vector.method: windbarb`.",
            "",
            "## Product reference",
            "",
        ]
    )

    for status in STATUS_ORDER:
        items = by_status.get(status, [])
        if not items:
            continue

        lines.append(f"### {status.title()}")
        lines.append("")
        lines.append(
            "| UI key | Slug | Display name | Dataset | Scalar | Vector | Colormap | Levels | Unit | Deployed |"
        )
        lines.append(
            "|--------|------|--------------|---------|--------|--------|----------|--------|------|----------|"
        )

        for slug, product in sorted(items, key=lambda x: x[0]):
            var_cfg = variables.get(slug, {})
            plot = product.get("plot", {})
            scalar = plot.get("scalar", {})
            vector = plot.get("vector", {})
            ui_key = product.get("ui_key") or "—"
            if ui_key is None:
                ui_key = "—"

            vector_str = vector.get("method", "none")
            if vector.get("overlay"):
                vector_str += " (overlay)"

            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{ui_key}`",
                        f"`{slug}`",
                        var_cfg.get("var2display", slug),
                        product.get("dataset", "—"),
                        scalar.get("method", "—"),
                        vector_str,
                        format_colormap(var_cfg),
                        format_levels(var_cfg),
                        var_cfg.get("unit", "—"),
                        deployment_note(slug, product, deployed),
                    ]
                )
                + " |"
            )

        lines.append("")

    palette_products: dict[str, list[str]] = {}
    for slug, product in products.items():
        var_cfg = variables.get(slug, {})
        key = var_cfg.get("palette")
        if key:
            palette_products.setdefault(key, []).append(slug)

    lines.extend(
        [
            "## Nusawave colormap palettes",
            "",
            "All shaded products use discrete palettes in "
            "[`plotter/core/colormaps.py`](../plotter/core/colormaps.py), "
            "anchored to brand colors `#0B2340` (navy) and `#0B74DE` (blue).",
            "",
            "| Palette key | Products |",
            "|-------------|----------|",
        ]
    )
    for key in sorted(palette_products):
        slugs = ", ".join(f"`{s}`" for s in palette_products[key])
        lines.append(f"| `{key}` | {slugs} |")

    lines.extend(
        [
            "",
            "## Windbarb support",
            "",
            "Wind products can opt in to windbarbs by setting in `plotter/config/config.yaml`:",
            "",
            "```yaml",
            "products:",
            "  wind:",
            "    plot:",
            "      vector:",
            "        method: windbarb",
            "        overlay: true",
            "```",
            "",
            "Wave products (`swh`, `swell`) default to quiver overlays. "
            "`seacurrent` uses a filled speed field plus quiver direction.",
            "",
            "## Configuration files",
            "",
            "| File | Purpose |",
            "|------|---------|",
            "| [`plotter/config/config.yaml`](../plotter/config/config.yaml) | Product catalog, plot metadata, styling |",
            "| [`assets/config/config.json`](../assets/config/config.json) | Frontend deployment catalog (from map scan) |",
            "| [`plotter/handlers/`](../plotter/handlers/) | Per-product load/plot plugins |",
            "",
        ]
    )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate map forecast product catalog markdown")
    parser.add_argument("--output", default=str(CATALOG_PATH))
    args = parser.parse_args()

    yaml_cfg = load_param_config()
    deployed = scan_deployed_assets()
    markdown = render_markdown(yaml_cfg, deployed)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(markdown + "\n")
    print(f"[INFO] Wrote {out}")


if __name__ == "__main__":
    main()
